services:
  yuchat-frontend:
    image: nginx:alpine
    container_name: yuchat-frontend
    volumes:
      - /deploy/h5:/usr/share/nginx/html:ro
      - /deploy/h5/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - yuchat_yuchat_net
    restart: always

networks:
  yuchat_yuchat_net:
    external: true